#
# @file
# Travis CI config file for running our Behat examples.
#

language: php

php:
  - 5.6
  - 7.0

addons:
  apt:
    packages:
      - unzip
      - sqlite3

cache:
  directories:
    # @see https://github.com/travis-ci/travis-ci/issues/4579
    - $HOME/.composer/cache/files

before_install:
  # PHP 5.6 is memory hungry.
  - echo 'memory_limit = 2G' >> ~/.phpenv/versions/$(phpenv version-name)/etc/conf.d/travis.ini

install:
  - composer install
  - composer create-project --stability dev --no-interaction --no-dev drupal-composer/drupal-project drupal-test-site
  - ./drupal-test-site/vendor/bin/drush --yes --root=./drupal-test-site/web/ site-install --db-url=sqlite:///dev/shm/behat-test.sqlite --account-pass=$BEHAT_DRUPAL_ADMIN_PASSWD
  - cp /dev/shm/behat-test.sqlite ./tests/test-db/behat-test.sqlite

before_script:
  - |
    ./drupal-test-site/vendor/bin/drush --yes --root=./drupal-test-site/web/ runserver &
    DRUSH_SERVER_PID=$!
  - until netstat -ln | grep '127.0.0.1:8888'; do sleep 1; done

script: composer test

after_script:
  - kill $DRUSH_SERVER_PID
